title: "Mosher/Rapp Home Movies"
email: cmosher01@gmail.com
description: Copyright © 2005–2019, Christopher Alan Mosher, Shelton, Connecticut, USA.
repository: https://github.com/cmosher01/Mosher-Rapp-Home-Movies
github_username: cmosher01
baseurl: /Mosher-Rapp-Home-Movies
markdown: kramdown
theme: minima
collections:
  extras:
    output: true
  films:
    output: true
include:
  - '_*'
defaults:
  - scope:
      type: films
    values:
      layout: film
